<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Register Form</title>
  </head>
  <body>

    <div class="container">
      
      <?php include_once('_menu.phtml')?>


      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">User</th>
            <th scope="col">Title</th>
            <th scope="col">Created At</th>
            <th scope="col">Active</th>
          </tr>
        </thead>
        <tbody>

        <?php foreach ($data as $gb): ?>
          <tr>
            <th scope="row"><?=$gb['first_name'] . ' ' . $gb['last_name']?></th>
            <td><?=$gb['title']?></td>
            <td><?=$gb['created_at']?></td>
            <td>
              <?php if ($gb['is_active'] == 1): ?>
                <button type="button" data-active="1" data-id="<?=$gb['id']?>" class="btn btn-sm btn-success is_active">Validated</button>
              <?php else: ?>
                <button type="button" data-active="0" data-id="<?=$gb['id']?>" class="btn btn-sm btn-warning is_active">Waiting</button>
              <?php endif ?>
            </td>
          </tr>
        <?php endforeach ?>

        </tbody>
      </table>

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  
    <script>
      $('.is_active').on( "click", function() {
        var button = $(this);
        $.ajax({
          type: "GET",
          url: '/guestbook/validate/' + $(this).data('id'),
        })
        .done(function(result) {
          var objData = JSON.parse(JSON.stringify(result));
          if (objData.data.result == 0) {
            return;
          }
          
          if (button.data('active')) {
            button.data('active', 0).removeClass('btn-success').addClass('btn-warning').text('Waiting');
          } else {
            button.data('active', 1).removeClass('btn-warning').addClass('btn-success').text('Validated');
          }
        })
        .fail(function(result) {
          console.log(result);
        });


      });
    </script>
    
  </body>
</html>